aesdchar_load script to load the AESD character device module

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -18,12 +18,12 @@ else
     group="wheel"
 fi
 
-if [ -e ${module}.ko ]; then
+if [ -e ${MODULE_PATH}/${module}.ko ]; then
     echo "Loading local built file ${module}.ko"
     insmod ${MODULE_PATH}/$module.ko $* || exit 1
 else
-    echo "Local file ${module}.ko not found, attempting to modprobe"
-    modprobe ${module} || exit 1
+    echo "File ${module}.ko not found at path ${MODULE_PATH}"
+    #modprobe ${module} || exit 1
 fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
